### ISSUE TITLE
stuck at located connecting

### ISSUE THREAD

**Issue by diits3** [ama6nen/enetproxy#103]
It is stuck at located connecting, I've built it correctly with no errors, any help? Is it updated?

**Comment by qatroxx** [comment]
иди нахуй

**Comment by diits3** [comment]
> иди нахуй

Sorry, I do not speak the language of Stalin

**Comment by diits3** [comment]
Does GT have a new ip/port again? Or is this a problem on Ubisofts end?

**Comment by MarmoriPelaa** [comment]
Just send a HTTP 1.0 POST request to growtopia1.com/growtopia/server_data.php using curl:
`
curl -X POST --http1.0 growtopia1.com/growtopia/server_data.php
`
And retrieve the ip/port there.

As far as I know, the port changes each time the server restarts.

This could be automated by making the request from the proxy via a HTTP library.

**Comment by qatroxx** [comment]
> > иди нахуй
> 
> 
> 
> Sorry, I do not speak the language of Stalin

ok bratan

**Comment by ama6nen** [comment]
Not planning to fix for now, someone can make pr for getting the correct port and server from server_data if they want to
