### ISSUE TITLE
stuck at located server connecting

### ISSUE THREAD

**Issue by Furkan125** [ama6nen/enetproxy#106]
I use HxD and change growtopia1.com and growtopia2.com to localhost, i open growtopia and proxy but when i try to join game stuck at located server connecting.

**Comment by NoelGamer** [comment]
Same problem but I use hosts file. Tried to port forward all the ports mentioned in the solution and tried all the ips and ports from previous versions but still stuck.

**Comment by ama6nen** [comment]
Not planning to fix for now, someone can make pr for getting the correct port and server from server_data if they want to
