### ISSUE TITLE
stuck at located server connecting

### ISSUE THREAD

**Issue by arky-arky** [ama6nen/enetproxy#107]
whenever i run proxy with 127.0.0.1 growtopia1.com 127.0.0.1 growtopia2.com hosts file im stuck at located server connecting, anyone can help me fix this?

**Comment by F3R07** [comment]
edit the port to this 17195 or this 17198

**Comment by Furkan125** [comment]
> edit the port to this 17195 or this 17198

how can i edit the port ?

**Comment by ama6nen** [comment]
Not planning to fix for now, someone can make pr for getting the correct port and server from server_data if they want to

**Comment by bexpg000** [comment]
> > edit the port to this 17195 or this 17198
> 
> how can i edit the port ?

http://growtopia1.com/growtopia/server_data.php

**Comment by NotKonishi** [comment]
> Not planning to fix for now, someone can make pr for getting the correct port and server from server_data if they want to

![image](https://user-images.githubusercontent.com/74392505/100679146-cf93ed80-33a9-11eb-9e4a-20afe9496cce.png)

how about try curl lib

**Comment by Furkan125** [comment]
Which file should I write the codes you provided?

**Comment by Furkan125** [comment]
> > Not planning to fix for now, someone can make pr for getting the correct port and server from server_data if they want to
> 
> ![image](https://user-images.githubusercontent.com/74392505/100679146-cf93ed80-33a9-11eb-9e4a-20afe9496cce.png)
> 
> how about try curl lib feel lazy to make PR but i give some hint how to get data from server_data http

Which file should I write the codes you provided?

**Comment by NotKonishi** [comment]
> Which file should I write the codes you provided?

https://github.com/curl/curl
