### ISSUE TITLE
Auethentication_error 1

### ISSUE THREAD

**Issue by ColinAA** [ama6nen/enetproxy#117]
I've edited the port to be 17196 as it seems to be now and when I try to login it shows me all these details that seems to be correct, but it also gives me an authentication error in the console. It's stuck on Loggin on ...
Here is the console log,

> enet proxy by ama
> HTTP server is running.
> [SERVER]: started the enet server.
> [CLIENT]: Started enet client
> Server & client proxy is running.
> [HTTP]: 127.0.0.1 - POST /growtopia/server_data.php
> [HTTP]: got server data request.
> [SERVER]: Connecting to server.
> [SERVER]: port is 17196 and server is 213.179.209.168
> [CLIENT]: Started enet client
> [CLIENT]: connection event
> [SERVER]: Got unknown packet of type 1.
> [SERVER]: Generic text: tankIDName|ColinCB37
> tankIDPass|removed
> requestedName|JoyHeadF
> f|1
> protocol|117
> game_version|3.51
> fz|7087272
> lmode|0
> cbits|0
> player_age|22
> GDPR|1
> hash2|-removed
> meta|ni.com
> fhash|-removed
> rid|removed
> platformID|0
> deviceVersion|0
> country|se
> hash|removed
> mac|removed
> wk|
> zf|removed
> [SERVER]: Spoofing login info
> [CLIENT]: Tracking packet: eventType|0
> eventName|102_PLAYER.AUTHENTICATION
> Name|^^ColinCB37
> Authenticated|0
> Authentication_error|1`

( I have removed some details just to be sure ) 

I don't know if that's it but it says ```
"requestedName|JoyHeadF
f|1"
``` and that is the guest name and not the GrowID. 
I am not sure what I am doing wrong but can someone atleast tell me what Authentication_error|1` means.
Thx

**Comment by ama6nen** [comment]
https://github.com/ama6nen/enetproxy/releases/tag/V3.51
