### ISSUE TITLE
Not working with 3.5.1

### ISSUE THREAD

**Issue by zhiyuanwang123** [ama6nen/enetproxy#118]
The proxy does connect to the server, but the server wasn't responding. 
[HTTP]: 127.0.0.1 - POST /growtopia/server_data.php
[HTTP]: got server data request.
[SERVER]: Connecting to server.
[SERVER]: port is 17198 and server is 213.179.209.168
[CLIENT]: Started enet client

The port is from http://growtopia1.com/growtopia/server_data.php, and it should be correct.

**Comment by RefetBilal** [comment]
Same issue. @ama6nen can look why we cant use proxy rn ?

**Comment by F3R07** [comment]
try add IPV6

**Comment by RefetBilal** [comment]
@F3R07 What you mean with adding IPV6 ? Can explain a bit?

**Comment by Zavins** [comment]
@RefetBilal did you fix it yet?

**Comment by RefetBilal** [comment]
@Zavins Nope. I dont know how to fix it yet

**Comment by StrafeGod** [comment]
@F3R07 can you help us ? im casino hoster and i need the proxy fast :(

**Comment by zhiyuanwang123** [comment]
@StrafeGod which team are you in?

**Comment by StrafeGod** [comment]
@zhiyuanwang123  Turkish team min 20 max infinite  tayfa csn and birlik csn trusted

**Comment by ama6nen** [comment]
https://github.com/ama6nen/enetproxy/releases/tag/V3.51
