### ISSUE TITLE
Wrench pull error! I need help!

### ISSUE THREAD

**Issue by moonsoftwares** [ama6nen/enetproxy#130]
![image](https://user-images.githubusercontent.com/77073711/104013072-fbcd3600-51c1-11eb-86bd-d2e891fd783f.png)
When I add the code there
![image](https://user-images.githubusercontent.com/77073711/104014382-f96bdb80-51c3-11eb-846c-d61617d56002.png)
gives an error like this please help

**Comment by ama6nen** [comment]
fault is within substr, find probably cannot find embed_data|netID and returns -1

**Comment by SrMotion** [comment]
Change substr string to this:
std::string netidyarragi = content.substr(content.find("embed_data|netID") + 17, content.length() - content.find("embed_data|netID") - 1);

so its deleting strings first 17 letter and takes lastest
and netid output like that
embed_data|netID|1234
and you get like this: 1234
