### ISSUE TITLE
Aap Bypass not working 3.52

### ISSUE THREAD

**Issue by greyhoven** [ama6nen/enetproxy#138]
I receive the verify on your email thing when I connect. Even tho proxy is working, I conclude that Ubisoft might have changed things on their AAP thing.

**Comment by beamerhvh** [comment]
Patched. Used MAC to bypass AAP now.

**Comment by Jupez12** [comment]
How to bypass with mac?

**Comment by beamerhvh** [comment]
j use a stealer with that built in. its kinda complicated, you change your mac to the victims mac.

**Comment by Jupez12** [comment]
How to change my mac i dont have a gabb and tmac not working

**Comment by ama6nen** [comment]
Fixed
