### ISSUE TITLE
how to send a punch 

### ISSUE THREAD

**Issue by yEsPaP** [ama6nen/enetproxy#142]
in events.cpp i try:

```
else if (find_command(chat, "bruh ")) {
            std::string bruh = chat.substr(6);
            if (bruh == "yes") {
                g_server->send(false, "action|Punch|tilex|9|\n|tiley|23|\n", 3);
            } 
            return true;
        }
```

it aint punching : (

**Comment by SrMotion** [comment]
punch is raw packet.

**Comment by yEsPaP** [comment]
> punch is raw packet.

any example to send it?

**Comment by qatroxx** [comment]
genius

> in events.cpp i try:
> 
> ```
> else if (find_command(chat, "bruh ")) {
>             std::string bruh = chat.substr(6);
>             if (bruh == "yes") {
>                 g_server->send(false, "action|Punch|tilex|9|\n|tiley|23|\n", 3);
>             } 
>             return true;
>         }
> ```
> 
> it aint punching : (

genius

**Comment by yEsPaP** [comment]
> genius
> 
> > in events.cpp i try:
> > ```
> > else if (find_command(chat, "bruh ")) {
> >             std::string bruh = chat.substr(6);
> >             if (bruh == "yes") {
> >                 g_server->send(false, "action|Punch|tilex|9|\n|tiley|23|\n", 3);
> >             } 
> >             return true;
> >         }
> > ```
> > 
> > 
> > it aint punching : (
> 
> genius

i know

**Comment by yEsPaP** [comment]
> punch is raw packet.
```
        } else if (find_command(chat, "hack")) {
            gameupdatepacket_t packet{};
            packet.m_type = PACKET_TILE_CHANGE_REQUEST;
            packet.m_player_flags = 13;
            packet.m_item = 1020;
            packet.m_int_data = 6;
            packet.m_vec_x = 2956;
            packet.m_vec_y = 802;
            packet.m_state1 = 93;
            packet.m_state2 = 25;
            packet.m_data = 17630;
            g_server->send(false, NET_MESSAGE_GAME_PACKET, (uint8_t*)&packet, sizeof(gameupdatepacket_t));
            return true;
```

still not working.
any idea?
