### ISSUE TITLE
wrench issue 

### ISSUE THREAD

**Issue by armandasgt** [ama6nen/enetproxy#143]
i click on wrench on doesnt even do anything can help?
![armandz](https://user-images.githubusercontent.com/77745691/105211804-8aff1580-5b01-11eb-884c-0fe5ce46588e.PNG)

**Comment by SrMotion** [comment]
put code to OnDialogRequest.

**Comment by armandasgt** [comment]
> put code to OnDialogRequest.

wdym by saying that

**Comment by qatroxx** [comment]
> > put code to OnDialogRequest.
> 
> wdym by saying that

            variantlist_t packet{ "OnDialogRequest" };
