### ISSUE TITLE
getting a error (The instruction at 0x00007FF644184E1A referenced memory at 0x(a bunch of zeros), The memory could not be read.)

### ISSUE THREAD

**Issue by iiLeafy** [ama6nen/enetproxy#149]
So i've been getting this error even with a fresh copy of the source and idk why. [ignore the "dny.wtf" thingy, its just a image effect i use]
![8f66338](https://user-images.githubusercontent.com/60797172/106393419-af12fe80-63ff-11eb-894f-deef4f2b55af.png)

also the code errors at this
``` /* Add streams to fd_sets */
  for (st = srv->streams; st; st = st->next) {
    if (st->state >= STATE_SENDING_STATUS) {
      FD_SET(st->sockfd, &fds_write);
    } else {
      FD_SET(st->sockfd, &fds_read);
    }
    if (st->sockfd > max_fd) max_fd = st->sockfd;
  }
```

with the reason of: "Exception thrown: read access violation. **srv** was nullptr."
the error is in the sandbird.c file at line 883

**Comment by GuckTubeYT** [comment]
Try run as administrator

**Comment by GuckTubeYT** [comment]
Or, port 80 is already used in other app (sorry for bad grammar)

**Comment by iiLeafy** [comment]
> Try run as administrator

Already tried doesnt work.

> Or, port 80 is already used in other app (sorry for bad grammar)

Already stopped all http processes and made it be  available, but its a error in the code i believe not 80 being used

**Comment by GuckTubeYT** [comment]
When you login, or when you open the app?

**Comment by GuckTubeYT** [comment]
When you open the app, and then error, its because = port 80 is already used or you must run as administrator

**Comment by iiLeafy** [comment]
> When you open the app, and then error, its because = port 80 is already used or you must run as administrator

Yeah i understood that port 80 is used but i deleted my antivirus mcafee it was using it and i dont need the av, but when i check netstat -ab it still shows same ip as av but it cant figure out whats using it

**Comment by iiLeafy** [comment]
Nvm fixed looks like Mantle.exe was using port 80, but it was quite advanced to find for whatever reason, it never showed me mantles pid only systems pid
