### ISSUE TITLE
Hell Me Please WİNSOCK_DESPRACTED_NO_WARNİNGS 

### ISSUE THREAD

**Issue by heysurfer** [ama6nen/enetproxy#15]
intenet_address_set_host (ENetAddress * address, const char * name){    struct hostent * hostEntry;    hostEntry = gethostbyname (name);    if (hostEntry == NULL ||        hostEntry -> h_addrtype != AF_INET)      return enet_address_set_host_ip (address, name);    address -> host = * (enet_uint32 *) hostEntry -> h_addr_list [0];    return 0;}  

İ GET ERROR

**Comment by sametblk** [comment]
give me discord

**Comment by heysurfer** [comment]
> give me discord

HeySurfer#0654

**Comment by sametblk** [comment]
i cant add you add me....  
samo#1549

**Comment by ama6nen** [comment]
build x86 release
