### ISSUE TITLE
Raw Packets not working idk

### ISSUE THREAD

**Issue by yEsPaP** [ama6nen/enetproxy#150]
Hey ama, ik you quit helping the public, but maybe someone knows this in general.

idk what i did here to add SendPacketRaw (don't know wtf i'm doing at all pls help): https://github.com/yEsPaP/enetproxy/commit/1b39b560bd996e251b1fa1e4baac2f9a96e51eca

and now when I have that, I'm trying to send punch to 1 block in front of me (x+1), with the above code:

```
        } else if (find_command(chat, "test")) {
            server::TankPacket data;
            auto& me = g_server->m_world.local;
            data.PunchX = me.pos.m_x / 32 + 1;
            data.PunchY = (me.pos.m_y / 32);
            data.MainValue = 18;
            data.X = me.pos.m_x;
            data.Y = me.pos.m_y;
            data.NetID = -1;
            data.PacketType = 3;
            data.ExtDataMask = 0;
            g_server->sendraw(false, g_server->PackForSendingRaw(&data), 56, 0, 4);
```

Sadly It does not work for me, but it does get to https://github.com/yEsPaP/enetproxy/blob/master/proxy/server.cpp#L301, and prints that it sent the packet.

I copied the some of the values from playingo for the punch
https://github.com/playingoDEERUX/growbrewproxy/blob/master/GrowbrewProxy/MainForm.cs#L2244

Any help/explanations appreciated.

Thanks.

EDIT: force pushed both commits as 1 so updated commit link

420TH EDIT:
so i changed client from false to true and its visual only ???
https://streamable.com/mpwct6

EDIT again: code updated for 1 block in front of me instead of below me, because below me bans me when sending to client

**Comment by iiLeafy** [comment]
well growbrew is c# so thats probably a reason but idk

**Comment by yEsPaP** [comment]
> well growbrew is c# so thats probably a reason but idk

i know, i just copied extdatamask values. growtopia is growtopia.

do you know how to send raw packtes?

**Comment by yEsPaP** [comment]
UPDATE: Changed some values and https://imgur.com/a/mOgxv9b happened

**Comment by yEsPaP** [comment]
OMG i fixed it, it works!

**Comment by yEsPaP** [comment]
no its only visual tf

**Comment by yEsPaP** [comment]
https://streamable.com/mpwct6

**Comment by heysurfer** [comment]
what's your dc?

**Comment by yEsPaP** [comment]
> what's your dc?

Henris#3330

**Comment by heysurfer** [comment]
check dm!

**Comment by qatroxx** [comment]
server::TankPacket data;  👍 👍 👍

**Comment by qatroxx** [comment]
its not growbrew proxy

**Comment by yEsPaP** [comment]
> its not growbrew proxy

well ofc? tf u trying to say

**Comment by yEsPaP** [comment]
fixed it by setting some values to 0..

**Comment by Drithh** [comment]
> fixed it by setting some values to 0..

what value did you set to 0, I have followed everything you did. but mine happened the same as in your video
