### ISSUE TITLE
How can i change chat color and print dropped items

### ISSUE THREAD

**Issue by HowDoiPlayGt** [ama6nen/enetproxy#152]

**Comment by qatroxx** [comment]
onconsolemessage

**Comment by ama6nen** [comment]
action|log (type 3 sendpacket) or OnConsoleMessage (type 4 (raw) variantlist)

**Comment by HowDoiPlayGt** [comment]
> action|log (type 3 sendpacket) or OnConsoleMessage (type 4 (raw) variantlist)

how

**Comment by StexHub** [comment]
> action|log (type 3 sendpacket) or OnConsoleMessage (type 4 (raw) variantlist)

ama this guy prob installed visual studio just to compile this because his friend told him he can /ghost and scam trust test kids. i dont think he's gonna understand that
