### ISSUE TITLE
Help Please

### ISSUE THREAD

**Issue by heysurfer** [ama6nen/enetproxy#16]
[
![Stock ](https://user-images.githubusercontent.com/58826689/74377323-c030bd00-4df4-11ea-80d2-6ad3df880aa9.PNG)
](url)

HOST FİLE  
#     growtopia1    127.0.0.1   
#     growtopia2        127.0.0.1          

DC HeySurfer#0654

**Comment by whotakeaurumk** [comment]
I cant find ur discord use this link and join my server https://discord.gg/wKEu5K6
