### ISSUE TITLE
what is Authentication Error|1 because i get it :(

### ISSUE THREAD

**Issue by LaceP** [ama6nen/enetproxy#161]
[SERVER]: Spoofing login info
[CLIENT]: Tracking packet: eventType|0
eventName|102_PLAYER.AUTHENTICATION
Name|^^AccountName
Authenticated|0
Authentication_error|1

**Comment by ama6nen** [comment]
Not sure, probably has to do with name being ^^AccountName (At least I think it should be ur name for gt)

**Comment by LaceP** [comment]
its my name

**Comment by LaceP** [comment]
and pass is correct
