### ISSUE TITLE
How can i know what block is placed in specific tilex tiley

### ISSUE THREAD

**Issue by yEsPaP** [ama6nen/enetproxy#165]
title says all

my best attempt in server.cpp

```
                                case 3:
                                    structs = unpackPlayerMoving(GetStructPointerFromTankPacket(event.packet));
                                    if (structs->NetID == g_server->m_world.local.netid) {
                                        if (structs->MainValue == 18) {
                                            gt::placed = false;
                                        }
                                    }
                                    break;
```

while it works, it changes that block broken when it breaks

but this gives 0 info what block i actually destroyed, placed etc..

is there a way i can see what block id is in lets say: tilex 0 tiley 0, also dropped items uid

**Comment by yEsPaP** [comment]
also how to send raw packet + delay?
void server::send(bool client, int32_t type, uint8_t* data, int32_t len)
i managed to get the delay with creating new thread, but the proxy crashes after some time cause not thread safe

**Comment by ama6nen** [comment]
Idk if you even need anything anymore, but it is that packet type.
The block id and coordinates should be in the struct.

As for delay, you can use timer, or a mutex for thread safety or something similar I guess

**Comment by yEsPaP** [comment]
> Idk if you even need anything anymore, but it is that packet type.
> The block id and coordinates should be in the struct.
> 
> As for delay, you can use timer, or a mutex for thread safety or something similar I guess

Youre right i dont need it anymore forgot to closed😅
