### ISSUE TITLE
Segmentation Fault (core dumped) when authenticating

### ISSUE THREAD

**Issue by PocXC** [ama6nen/enetproxy#169]
Operating System: Ubuntu

![image](https://user-images.githubusercontent.com/80333919/110480186-2fc0cb00-8121-11eb-83b3-61801ebfe112.png)

**Comment by yEsPaP** [comment]
@ama6nen fix when

**Comment by ama6nen** [comment]
no clue what is the problem so dont know

**Comment by yEsPaP** [comment]
> Operating System: Ubuntu
> 
> ![image](https://user-images.githubusercontent.com/80333919/110480186-2fc0cb00-8121-11eb-83b3-61801ebfe112.png)



> Operating System: Ubuntu
> 
> ![image](https://user-images.githubusercontent.com/80333919/110480186-2fc0cb00-8121-11eb-83b3-61801ebfe112.png)

try running gdb if you know how to,

or add print statements with line numbers on many lines till you find which one is faulty.

I cant try this now because I switched from real Linux to WSL2 and I can't get proxy on wsl, gt on windows to work.

**Comment by GuckTubeYT** [comment]
Try this = https://github.com/ama6nen/enetproxy/pull/173
