### ISSUE TITLE
Read Item In Inventory

### ISSUE THREAD

**Issue by Drithh** [ama6nen/enetproxy#176]
is it possible to see list of all items in inventory ?

i saw this enum 
PACKET_MODIFY_ITEM_INVENTORY (13)  when i interact with inventory (taking dropped items)
PACKET_SEND_INVENTORY_STATE (9) when first logon

**Comment by ama6nen** [comment]
Yeah, you have to serialize it from raw bytes.

I might add some framework for reading/saving inventory items at some point

**Comment by Drithh** [comment]
well thanks, can't wait to use that features
