### ISSUE TITLE
update issue

### ISSUE THREAD

**Issue by BooperCoomer** [ama6nen/enetproxy#179]
![image](https://user-images.githubusercontent.com/78278770/113464851-06facf80-945a-11eb-83f8-371607ac1e0b.png)

Always show like this.
but my gt alr up to date
![image](https://user-images.githubusercontent.com/78278770/113464869-1e39bd00-945a-11eb-9cd6-0802bcd35293.png)

**Comment by heysurfer** [comment]
https://github.com/ama6nen/enetproxy/blob/master/proxy/gt.cpp#L6
std::string gt::version = "3.60";

**Comment by BooperCoomer** [comment]
how to bypass aap with proxy?
![image](https://user-images.githubusercontent.com/78278770/113465374-af5e6300-945d-11eb-8d20-b7fcfbb26993.png)
![image](https://user-images.githubusercontent.com/78278770/113465380-bb4a2500-945d-11eb-897a-d882a2bc67f7.png)

**Comment by heysurfer** [comment]
` exit(0); ` on event.cpp

**Comment by BooperCoomer** [comment]
what do you mean with exit(0);?

**Comment by ama6nen** [comment]
aap bypass patched
