### ISSUE TITLE
Exception Thrown Error

### ISSUE THREAD

**Issue by omrtozd** [ama6nen/enetproxy#18]
![image](https://user-images.githubusercontent.com/30231311/74400136-1ec65d00-4e2e-11ea-8576-5313299a3651.png)

my discord nickname: omrtozd#6320, i already sent request to samo

**Comment by omrtozd** [comment]
I saw an old issue and ran it with release x86. I'm getting this now.
![image](https://user-images.githubusercontent.com/30231311/74400375-c2177200-4e2e-11ea-9f0c-14ed65c15d73.png)

**Comment by omrtozd** [comment]
![image](https://user-images.githubusercontent.com/30231311/74401266-c729f080-4e31-11ea-9da4-45a9e0ec85ef.png)
yeah and im getting this too

**Comment by omrtozd** [comment]
So far, so good. I deleted all things about captcha. Now I can run it but I'm getting this:
![image](https://user-images.githubusercontent.com/30231311/74401630-f2f9a600-4e32-11ea-8968-bfd479eaa01c.png)

**Comment by omrtozd** [comment]
I'm getting this error at cmd: [HTTP] Failed to start HTTP server.

**Comment by omrtozd** [comment]
Why the fuck are you closed this? It still gives error.

**Comment by DrKfir** [comment]
@omrtozd If you still didn't solve it DO:
1. Run CMD as administrator.
2. Write command "net stop was /y"
3. Wait until it's done.
4. Enjoy (:
5. If still not work try to uninstall Xampp if you have it!
