### ISSUE TITLE
why http server

### ISSUE THREAD

**Issue by yEsPaP** [ama6nen/enetproxy#183]
why is it needed ?

**Comment by Gangsteri** [comment]
For handling POST requests. Here is good documentation on how enet proxy works check it out [](https://github.com/GrowtopiaNoobs/GrowDocs)

**Comment by yEsPaP** [comment]
> For handling POST requests. Here is basic documentation on how enet proxy works check it out https://github.com/GrowtopiaNoobs/GrowDocs

ok thanks
