### ISSUE TITLE
About AAP bypass

### ISSUE THREAD

**Issue by mfmosp** [ama6nen/enetproxy#184]
Is it possible to bypass AAP with proxy if we know the target account's mac adress? If the answer is yes, then how? (What and where to change in code). If the answer is no, then how to bypass AAP with the mac adress of the target account?

**Comment by DrOreo002** [comment]
I'm pretty sure APP is checking IP rather than mac, but if you want to try you can replace this line to your mac address
https://github.com/ama6nen/enetproxy/blob/9b0ee89827a8a10aaea43f975d9fc43e3aaa902c/proxy/events.cpp#L200

**Comment by rasothecoder** [comment]
i tried changing this auto mac = utils::generate_mac(); to auto mac = 62672097FDC0; but im getting error. Am I doing something wrong? Help pls.

**Comment by mfmosp** [comment]
> I'm pretty sure APP is checking IP rather than mac, but if you want to try you can replace this line to your mac address
> https://github.com/ama6nen/enetproxy/blob/9b0ee89827a8a10aaea43f975d9fc43e3aaa902c/proxy/events.cpp#L200

I have tried but thats not working, i even tried to change the generate_mac() function to return the specific mac adress but its still not working.

**Comment by mfmosp** [comment]
> I tried changing this "auto mac = utils::generate_mac();" to "auto mac = 62672097FDC0;" but im getting error. Am I doing something wrong? Help pls.

You have to change "auto mac = utils::generate_mac();" to "auto mac = "..." ;", you have to write the mac adress between the " " so compiler understand that this is a string not an integer, but when you write with auto compiler will say its char so you need to write it like "std::string mac = "..." ";

**Comment by DrOreo002** [comment]
> > I'm pretty sure APP is checking IP rather than mac, but if you want to try you can replace this line to your mac address
> > https://github.com/ama6nen/enetproxy/blob/9b0ee89827a8a10aaea43f975d9fc43e3aaa902c/proxy/events.cpp#L200
> 
> I have tried but thats not working, i even tried to change the generate_mac() function to return the specific mac adress but its still not working.

Then APP doesn't check for mac, you gotta find another way. If its the IP then no luck, the only way you can bypass it is by hacking the victim's email too

**Comment by mfmosp** [comment]
> > > I'm pretty sure APP is checking IP rather than mac, but if you want to try you can replace this line to your mac address
> > > https://github.com/ama6nen/enetproxy/blob/9b0ee89827a8a10aaea43f975d9fc43e3aaa902c/proxy/events.cpp#L200
> > 
> > 
> > I have tried but thats not working, i even tried to change the generate_mac() function to return the specific mac adress but its still not working.
> 
> Then APP doesn't check for mac, you gotta find another way. If its the IP then no luck, the only way you can bypass it is by hacking the victim's email too

Ok thanks.

**Comment by mfmosp** [comment]
> > I tried changing this "auto mac = utils::generate_mac();" to "auto mac = 62672097FDC0;" but im getting error. Am I doing something wrong? Help pls.
> 
> You have to change "auto mac = utils::generate_mac();" to "auto mac = "..." ;", you have to write the mac adress between the " " so compiler understand that this is a string not an integer, but when you write with auto, then compiler will say its char so you need to write it like "std::string mac = "..." ;"
