### ISSUE TITLE
cannot play the game with proxy 

### ISSUE THREAD

**Issue by thehooksgod** [ama6nen/enetproxy#186]
when I try to log in 

[SERVER]: started the enet server.
[CLIENT]: Started enet client
Server & client proxy is running.
[HTTP]: 127.0.0.1 - POST /growtopia/server_data.php
[HTTP]: got server data request.
[HTTP]: unknown request
[SERVER]: Connecting to server.
[SERVER]: port is 17198 and server is 213.179.209.168
[CLIENT]: Started enet client
[CLIENT]: connection event
[SERVER]: Got unknown packet of type 1.
[SERVER]: Generic text: tankIDName|mepro552
tankIDPass|mepro1027
requestedName|EinstDuck
f|1
protocol|129
game_version|3.62
fz|7967056
lmode|0
cbits|0
player_age|50
GDPR|1
hash2|-2062081964
meta|ni.com
fhash|-716928004
rid|0155040004E5040B098639EA00E1A254
platformID|0
deviceVersion|0
country|tr
hash|-1704924761
mac|30:9c:23:b0:4e:5f
wk|3DEA2C93379D87304CAF77D7648E745B
zf|-1564727311
[SERVER]: Spoofing login info
[CLIENT]: Tracking packet: eventType|0
eventName|102_PLAYER.AUTHENTICATION
Name|^^mepro552
Authenticated|0
Authentication_error|28

[CLIENT]: Game message: action|log
msg|`4UPDATE REQUIRED!`` : The `$V3.62`` update is now available for your device.  Go get it!  You'll need to install it before you can play online.
[CLIENT]: Game message: action|set_url
url|https://ubistatic-a.akamaihd.net/0098/27699/GrowtopiaInstaller.exe
label|Download Latest Version

[CLIENT]: Game message: action|logon_fail

[SERVER]: Game message: action|quit

it wouldnt let me log in , says update required.

**Comment by thehooksgod** [comment]
I updated the version to 3.62 but still no bypass on aap.

**Comment by qatroxx** [comment]
[SERVER]: port is 17198 and server is 213.179.209.168

**Comment by thehooksgod** [comment]
if (reset) {
        m_user = 0;
        m_token = 0;
        m_server = "213.179.209.168";
        m_port = 17198;
        
        still issue unresoveld , cannot bypass aap.

**Comment by qatroxx** [comment]
> if (reset) {
> m_user = 0;
> m_token = 0;
> m_server = "213.179.209.168";
> m_port = 17198;
> 
> ```
>     still issue unresoveld , cannot bypass aap.
> ```

port|17200  is the port

**Comment by iProB1** [comment]
kanka discordunu ver yardımcı olıyım
ProB1#1375

**Comment by Zenixas** [comment]
> I updated the version to 3.62 but still no bypass on aap.

idiot, this aap bypass methos id patched long time ago
