### ISSUE TITLE
can't connect private servers.

### ISSUE THREAD

**Issue by promanasd** [ama6nen/enetproxy#191]
Hello, firstly thanks for proxy but i have some problems. i tried to connect private server but not working.

server.cpp : 
![image](https://user-images.githubusercontent.com/83706783/120631386-7e57da00-c470-11eb-9ccf-195285d18ceb.png)

server.h :
![image](https://user-images.githubusercontent.com/83706783/120631519-a6dfd400-c470-11eb-9bcf-d8c4b95f1c64.png)

**Comment by GuckTubeYT** [comment]
Find "newUsingPacket" code

**Comment by GuckTubeYT** [comment]
Change it to false

**Comment by growtopianowner** [comment]
> Change it to false

still not working bruh

**Comment by GuckTubeYT** [comment]
Bruh, why you change the proxyport?

**Comment by GuckTubeYT** [comment]
Change the m_port, not m_proxyport

**Comment by promanasd** [comment]
> Change the m_port, not m_proxyport

bruhhhh i don't changing the proxyport just them changed m_port and m_server

**Comment by GuckTubeYT** [comment]
Try another server?
