### ISSUE TITLE
did growtopia fixed login spoof?

### ISSUE THREAD

**Issue by Erdal99** [ama6nen/enetproxy#192]
i cant bypass aap anymore (im not talking about 02:00 or another method i got victims mac, rid etc.) it was working on 3.62 but i think ubisoft fixed it on 3.63 anybody knows something about that?

**Comment by qatroxx** [comment]
fix

**Comment by Erdal99** [comment]
is there any new way to bypass aap with victims mac or rid or wk

**Comment by GuckTubeYT** [comment]
> is there any new way to bypass aap with victims mac or rid or wk

I dont know
