### ISSUE TITLE
Got banned

### ISSUE THREAD

**Issue by shainodev** [ama6nen/enetproxy#197]
I got banned with proxy.

I went in to a BFG world where was checkpoints in the BFG farm areas and I took the checkpoint and tp'd to my friend. Later some guy went farming and then got many gems and I respawned and took the gems but the game didn't like register picking them up and then I tried picking them up like going back and trying to pick them up again but it didn't pick them up and suddenly I just got game banned for 60 days lol. Fix please.

**Comment by ama6nen** [comment]
If it doesn't register something continuously and you keep doing it then it can lead to a ban, this is how it is in gt in general

**Comment by gangsterGT** [comment]
> If it doesn't register something continuously and you keep doing it then it can lead to a ban, this is how it is in gt in general

Pls fix inzernal ama6nen my hero <33333333333333
