### ISSUE TITLE
change roulette's packets

### ISSUE THREAD

**Issue by splexas** [ama6nen/enetproxy#199]
hi, is it possible to code myself, that the proxy will change roulette's packets, the number itself?

**Comment by promanasd** [comment]
OnConsoleMessage

**Comment by splexas** [comment]
https://github.com/ama6nen/enetproxy/blob/master/proxy/events.cpp#L295 what do i need to do with this? sry im new to coding

**Comment by yEsPaP** [comment]
> https://github.com/ama6nen/enetproxy/blob/master/proxy/events.cpp#L295 what do i need to do with this? sry im new in c/cpp coding

check if the text packet contains "spun the wheel" or something idk
and then change it before sending it
