### ISSUE TITLE
I get the 3.011 Error.

### ISSUE THREAD

**Issue by Tideath12** [ama6nen/enetproxy#21]
As i said in the title, i get an error that wants me to update the game to 3.011(but the game is already up to date), while entering the game, can somebody help?

**Comment by sametblk** [comment]
You need update version on gt.hpp (because proxy spoof login packet)

**Comment by Tideath12** [comment]
> You need update version on gt.hpp (because proxy spoof login packet)

There is no version on gt.hpp or gt.cpp

**Comment by Tideath12** [comment]
Nevermind i solved it lol
