### ISSUE TITLE
Need help? Read!

### ISSUE THREAD

**Issue by sametblk** [ama6nen/enetproxy#22]
You need help about proxy? You can get help from here but you need learn something before edit/remove something from proxy.

- **Learn to search something on google** about problems in visual studio or something like that.
- Don't want any code. Try to make it yourself. we are not your servants. **Write your code yourself.**

**Comment by xXAbood** [comment]
lele ok

**Comment by loli789** [comment]
can I bypass password door with proxy? It is possible?

**Comment by TheArmagan** [comment]
> can I bypass password door with proxy? It is possible?

probably not

**Comment by SpaceR3** [comment]
no

**Comment by vietor55** [comment]
im not able to get it working... i updated gt.cpp version to 3.40 but still not working

**Comment by finlnd** [comment]
i changed the version number and got 500+ errors. i'll have another look and update you

**Comment by noor0x07** [comment]
jesus, 500 errors by changing a string?

**Comment by finlnd** [comment]
> jesus, 500 errors by changing a string?

might have something to do with the uninstallation of something for c++ but like i had nothing wrong until i tried compiling. i'll reinstall my c++ and get back to you.

**Comment by Kahhe72** [comment]
When update?

**Comment by ryanCSharp** [comment]
**Is it possible to code something like growscan?**
