### ISSUE TITLE
Cannot set up HTTP server

### ISSUE THREAD

**Issue by omrtozd** [ama6nen/enetproxy#24]
I built the proxy with Release x86 and added hosts but still, I'm having a problem with setup the HTTP server. When I try to open proxy, i am getting this error: 
![image](https://user-images.githubusercontent.com/30231311/74568924-3a467a80-4f8a-11ea-9006-cbe11e933c1d.png)

When I want to see whats the problem, I'm getting this error and some warnings at Visual Studio: 
![image](https://user-images.githubusercontent.com/30231311/74569012-6feb6380-4f8a-11ea-9f47-8acc11fbdd5a.png)

I didn't change anything in code but cause of the a problem it gets srv null. I didn't see this problem from anyone, so the problem is me. But the part of that I don't understand, what can cause this.

**Comment by ama6nen** [comment]
Port 80 is most likely already in use by something else, if it's not that then you can just host server_data with the proxy server ip and port manually with something like xampp

**Comment by omrtozd** [comment]
Thanks, I fix it. If anyone has same problem, reach me from Discord omrtozd#6320. I'm so lazy to tell it.
