### ISSUE TITLE
Subserver issue

### ISSUE THREAD

**Issue by Stacix** [ama6nen/enetproxy#30]
When moving subservers through doors with doorIDs in the destination, the proxy crashes.

i.e Entering a door with destination WORLD1:DOOR1 will crash if WORLD1 is on a different subserver than the current world.

**Comment by ama6nen** [comment]
Will try fixing maybe in a week or so, until then if other people want to fix it they're free to send pr

**Comment by ama6nen** [comment]
The cause seemed to be that OnSendToServer has destination as ip|doorid, and normally it just erases the last character (erasing | due to having no id).
Pushed a fix for it now.
