### ISSUE TITLE
Problem when spamming packets

### ISSUE THREAD

**Issue by noobsteak** [ama6nen/enetproxy#31]
Proxy lags out and when trying to relog, Growtopia gets stuck at “Logging on...”
I’ve tried restarting proxy + GT Client multiple times which didn’t work. Then after waiting 5 minutes, I tried again and it works. What is the problem here? How do I fix it without restarting proxy or GT?

**Comment by ama6nen** [comment]
GT disconnects you when you send too many packets (not proxy problem), and the proxy just becomes out of sync because it ignores disconnect requests in-game, probably should add some way to detect if disconnect has happened

**Comment by noobsteak** [comment]
But how about cheap private servers using skidded codes?

**Comment by DrOreo002** [comment]
> But how about cheap private servers using skidded codes?
They don't filter if there's a packet spam?

**Comment by noobsteak** [comment]
It might have something to do with the GT game client. Anyways, I’ll try figuring it out.
