### ISSUE TITLE
Patched?

### ISSUE THREAD

**Issue by urpo3** [ama6nen/enetproxy#35]
I have an issue when i login in growtopia. The proxy automatically crashes when i try to login. I have the newest version of enetproxy too. Please reply what could be the problem.

**Comment by ama6nen** [comment]
I am not a magician, how am I supposed to know without no info
Works fine for me in 2.996, 3.01, and 3.011.

**Comment by urpo3** [comment]
> I am not a magician, how am I supposed to know without no info
> Works fine for me in 2.996, 3.01, and 3.011.

I dont get the logic unless proxy cannot run same time as some other softwares maybe? I tried closing stuff from task manager but didnt work either. Ill try to find the problem.

**Comment by noobsteak** [comment]
What is CDNContent for 2.996?

**Comment by DrOreo002** [comment]
> What is CDNContent for 2.996?

That's old why would you need it?. But if you still want to know here it is
```
[11:59:03 INFO]: Found a function packet!: OnSuperMainStartAcceptLogonHrdxs47254722215a
[11:59:03 INFO]:  > STRING[0]=OnSuperMainStartAcceptLogonHrdxs47254722215a INT_X[1]=-1203202545 STRING[2]=ubistatic-a.akamaihd.net STRING[3]=0098/CDNContent49/cache/ STRING[4]=cc.cz.madkite.freedom org.aqua.gg idv.aqua.bulldog com.cih.gamecih2 com.cih.gamecih com.cih.game_cih cn.maocai.gamekiller com.gmd.speedtime org.dax.attack com.x0.strai.frep com.x0.strai.free org.cheatengine.cegui org.sbtools.gamehack com.skgames.traffikrider org.sbtoods.gamehaca com.skype.ralder org.cheatengine.cegui.xx.multi1458919170111 com.prohiro.macro me.autotouch.autotouch com.cygery.repetitouch.free com.cygery.repetitouch.pro com.proziro.zacro com.slash.gamebuster STRING[5]=proto=91|choosemusic=audio/mp3/about_theme.mp3|active_holiday=0|server_tick=131229952|clash_active=1|drop_lavacheck_faster=1|isPayingUser=1|usingStoreNavigation=1|enableButtonClickedChecker=1|
```
(Taken from my java bot)
Anyway sorry for being kinda out of topic




> I have an issue when i login in growtopia. The proxy automatically crashes when i try to login. I have the newest version of enetproxy too. Please reply what could be the problem.

I'm not a magician either so I would need to see if there's any error log printed out by vs to be able to help you

**Comment by urpo3** [comment]
> > What is CDNContent for 2.996?
> 
> That's old why would you need it?. But if you still want to know here it is
> 
> ```
> [11:59:03 INFO]: Found a function packet!: OnSuperMainStartAcceptLogonHrdxs47254722215a
> [11:59:03 INFO]:  > STRING[0]=OnSuperMainStartAcceptLogonHrdxs47254722215a INT_X[1]=-1203202545 STRING[2]=ubistatic-a.akamaihd.net STRING[3]=0098/CDNContent49/cache/ STRING[4]=cc.cz.madkite.freedom org.aqua.gg idv.aqua.bulldog com.cih.gamecih2 com.cih.gamecih com.cih.game_cih cn.maocai.gamekiller com.gmd.speedtime org.dax.attack com.x0.strai.frep com.x0.strai.free org.cheatengine.cegui org.sbtools.gamehack com.skgames.traffikrider org.sbtoods.gamehaca com.skype.ralder org.cheatengine.cegui.xx.multi1458919170111 com.prohiro.macro me.autotouch.autotouch com.cygery.repetitouch.free com.cygery.repetitouch.pro com.proziro.zacro com.slash.gamebuster STRING[5]=proto=91|choosemusic=audio/mp3/about_theme.mp3|active_holiday=0|server_tick=131229952|clash_active=1|drop_lavacheck_faster=1|isPayingUser=1|usingStoreNavigation=1|enableButtonClickedChecker=1|
> ```
> 
> (Taken from my java bot)
> Anyway sorry for being kinda out of topic
> 
> > I have an issue when i login in growtopia. The proxy automatically crashes when i try to login. I have the newest version of enetproxy too. Please reply what could be the problem.
> 
> I'm not a magician either so I would need to see if there's any error log printed out by vs to be able to help you

Im not sure does this cause the problem but the proxy says "Unknown packet type 1" or something like that cant remember but it says it before the crash and theres no other errors.

**Comment by urpo3** [comment]
I mean 15-20 seconds before crash.

**Comment by DrOreo002** [comment]
Full logs or no help. Also don't run it via plain exe, use debug mode via Visual Studio to actually see whats wrong

**Comment by noobsteak** [comment]
Thanks @DrOreo002
