### ISSUE TITLE
pls help me

### ISSUE THREAD

**Issue by gucktubeyt2** [ama6nen/enetproxy#37]
i got this error

Severity	Code	Description	Project	File	Line	Suppression State
Error	C4996	'gethostbyname': Use getaddrinfo() or GetAddrInfoW() instead or define _WINSOCK_DEPRECATED_NO_WARNINGS to disable deprecated API warnings	proxy	C:\Users\Administrator\Desktop\enetproxy-master\proxy\enet\win32.c	93

**Comment by DrKfir** [comment]
build x86 release.
@gucktubeyt2
