### ISSUE TITLE
Proxy crash

### ISSUE THREAD

**Issue by akamusaz** [ama6nen/enetproxy#38]
![image](https://user-images.githubusercontent.com/46966600/75542395-6f41db00-5a28-11ea-86ca-cb4b9896722a.png)
Only happens right before login, proxy closes automatically. Hosts file is in the right place. Tried rebuilding many times.
Also I tried debugging it, leads to xstring
![image](https://user-images.githubusercontent.com/46966600/75543873-761e1d00-5a2b-11ea-8d26-3205696afbd3.png)

**Comment by ama6nen** [comment]
This happened to someone else as well, pushed a fix which should stop it from crashing

**Comment by akamusaz** [comment]
> This happened to someone else as well, pushed a fix which should stop it from crashing

I now get an auth error but atleast it works. Also, please unblock me on discord, i didn't read the git before messaging.

Arkku/Musaz#0704
