### ISSUE TITLE
Ama ip address 

### ISSUE THREAD

**Issue by Bexpg** [ama6nen/enetproxy#40]
![20200229_160856](https://user-images.githubusercontent.com/61095632/75608131-deddc600-5b0d-11ea-84b6-61df3f320ace.jpg)

**Comment by Bexpg** [comment]
109.240.26.153 how u know its real or no first dm he in discord after start ddos and u can see he will be disconnect

**Comment by Bexpg** [comment]
ok ? @ama6nen

**Comment by xXAbood** [comment]
@Bexpg 176.217.16.44 ok bro

**Comment by Bexpg** [comment]
@xXAbood  my old wifi service ip ok bro. ;)

**Comment by Bexpg** [comment]
Try ddos this ip and lets see i will disconnect or no

**Comment by xXAbood** [comment]
![image](https://user-images.githubusercontent.com/59313717/75609950-836c0200-5b26-11ea-929a-7bcf7bca0882.png)
ok

**Comment by Bexpg** [comment]
@xXAbood  u crying because i leaked ur cpp ok bro

**Comment by loanselot** [comment]
what is my ip

**Comment by Bexpg** [comment]
@loanselot  who is you retard i dont steal kids ip

**Comment by ama6nen** [comment]
not even correct, and you can stop being desperate for attention at this point

![](https://i.imgur.com/GzAOlP8.png)
