### ISSUE TITLE
help? Cannot open include file 

### ISSUE THREAD

**Issue by cucksexy** [ama6nen/enetproxy#42]
Error	C1083	 Cannot open include file: 'stdlib.h': No such file or directory	
Error	C1083	 Cannot open include file: 'winsock2.h': No such file or directory	
same with string.h if anyone can tell me a solution? dm me at Cuck#4083
Cuck#4083

**Comment by cucksexy** [comment]
![Capture](https://user-images.githubusercontent.com/61672220/75648080-e8a12e00-5cb3-11ea-9599-40a591ba0a42.PNG)
![Capture2](https://user-images.githubusercontent.com/61672220/75648083-e9d25b00-5cb3-11ea-8903-e47e43e49cb3.PNG)

**Comment by DrKfir** [comment]
What version of visual studio do you use?
@cucksexy

**Comment by cucksexy** [comment]
2019 @DrKfir

**Comment by DrKfir** [comment]
@cucksexy I think I had this problem before, but I forgot how to fix it, lol.
Try restart pc or something else or just google it.

**Comment by DrKfir** [comment]
@cucksexy https://stackoverflow.com/questions/19415521/cannot-open-include-file-with-visual-studio

**Comment by cucksexy** [comment]
Thanks I’ll let u know if it works
