### ISSUE TITLE
I Got error while build cpp

### ISSUE THREAD

**Issue by lixorhaxz** [ama6nen/enetproxy#45]
![Screenshot_2020-03-14-09-31-12-015_com microsoft rdc android](https://user-images.githubusercontent.com/47329758/76672332-d1790f00-65d6-11ea-8a32-ce9dd607d265.png)

**Comment by crandet2** [comment]
too bad fix it urself
-Crandetan

**Comment by lixorhaxz** [comment]
> too bad fix it urself
> -Crandetan

i fixed it
it works bro I swear

**Comment by herothedev** [comment]
then close this issue?

**Comment by axnanyt** [comment]
can help me i have the same error

**Comment by axnanyt** [comment]
fixed
