### ISSUE TITLE
when i type /ghost /proxy or any command, its doest work

### ISSUE THREAD

**Issue by GuckTubeYT** [ama6nen/enetproxy#46]
how to fix that

**Comment by herothedev** [comment]
bruh basics, you need to START the proxt and SET the HOSTS file right. not helping. its just... just a basic thing

**Comment by herothedev** [comment]
from readme: 
"Does not need separate http server
Use HxD or similar to edit "growtopia1.com" and "growtopia2.com" to "localhost" In growtopia binary.
Alternative: Use hosts file to set growtopia1 and growtopia2 to point to 127.0.0.1 if you want to
Start proxy -> Run localhost patched file (or normal with hosts) -> Works as supposed"
