### ISSUE TITLE
/kick all /ban all etc

### ISSUE THREAD

**Issue by nebuxd** [ama6nen/enetproxy#54]
need those things above

**Comment by noobsteak** [comment]
For each player in world, action|input /kick player name

**Comment by nebuxd** [comment]
> For each player in world, action|input /kick player name

source code?

**Comment by noobsteak** [comment]
Make it yourself..

**Comment by noobsteak** [comment]
Hint: check /kill

**Comment by MoanHawks** [comment]
action|wrench
action|dialog_return
