### ISSUE TITLE
AAP Bypass does not work.

### ISSUE THREAD

**Issue by zix3r** [ama6nen/enetproxy#58]
AAP Bypass does not work.
Tried multiple times with different IP, MAC, GUID, everything, it does not work.

**Comment by zix3r** [comment]
Also, when debugging, this error pops up:
Run-Time Check Failure #2 - Stack around the variable 'varlist' was corrupted. occurred

**Comment by ama6nen** [comment]
Fixed crashing and AAP bypass tested and working today
