### ISSUE TITLE
Is making an auto-typer after the roulette's delay possible?

### ISSUE THREAD

**Issue by Greanex** [ama6nen/enetproxy#65]
I'll make a command that auto-types in the chat after Roulette Wheel's delay. For example, he will write /type (number). Then, it will get the spinner's name and always auto-type(along with his IGN) this number's text in the chat when the punched Roulette Wheel's delay done. For example again; if the number that he wrote was 6, the player will auto-write `7[`w(spinner's name) spun the wheel and got `b0`w!`7]

But I have some questions before making it.

First of all, is this possible? Secondly, what is Roulette Wheel's delay?

_Note: This is a roulette number typer, not a hack. So everyone will have seen the text._

**Comment by XDarkTitan** [comment]
This is possible

**Comment by qatroxx** [comment]
onconsolemessage
