### ISSUE TITLE
Is making chat bubbles invisible when chatting is possible?

### ISSUE THREAD

**Issue by Greanex** [ama6nen/enetproxy#66]
I'll do a casino typer but I have a question about it. Is making chat bubbles invisible when chatting is possible?

**Comment by NotDark** [comment]
yes if chat message   is long

**Comment by playingoDEERUX** [comment]
It is possible by blocking the packet of type 18 from your client being sent to the server, this wont update any bubbles at all or by directly sending the action|input\n|text|(your text) packet with type 2 (GENERIC_TEXT)
I have also tried this by blocking the movement packet for fake spin, but people still find out somehow that its edited (spun a wheel myself and tried to trick the admin) - It didn't work, but I saw it being work for some others rarely...
