### ISSUE TITLE
Update Growtopia I fix Thx

### ISSUE THREAD

**Issue by kanser17** [ama6nen/enetproxy#87]
When I open growtopia it say update growtopia but my growtopia is lastest version I try to change ip but doesnt work pls help me

**Comment by ItsSickBoy** [comment]
go to gt.cpp, change this line "std::string gt::version = "3.37";"
with this line "std::string gt::version = "3.38";" and rebuild.

**Comment by demonicbae** [comment]
@kanser17 Now close the issue... because it's just finished already...
