### ISSUE TITLE
How did you find the surgery kill + legal brief thing

### ISSUE THREAD

**Issue by 4u7157** [ama6nen/enetproxy#88]
Just a question. How did you know what you needed to do to "use" the legal briefs here: https://github.com/ama6nen/enetproxy/commit/5a495ae1c0e725e9a3fa5a8c0316fca3029a712e

Thanks.

**Comment by demonicbae** [comment]
@4u7157 ama6nen Did not make it... Abood did so yeah...

**Comment by demonicbae** [comment]
You can ask abood...

**Comment by 4u7157** [comment]
who is abood?

**Comment by qatroxx** [comment]
> who is abood?

its abood

**Comment by demonicbae** [comment]
@4u7157 Abood is a Good Programmer... He who created surg hack / Legal...

**Comment by ama6nen** [comment]
Byko gave it to me, and he found it before abood.

**Comment by xXAbood** [comment]
> @4u7157 ama6nen Did not make it... Abood did so yeah...

Wasn't me, byko said the founder was loanselot but I waited until ama released it by himself.
