### ISSUE TITLE
The description will say it

### ISSUE THREAD

**Issue by demonicbae** [ama6nen/enetproxy#89]
How to disable the place packet like when you place u won't get any packet from placing If anyone knows please respond! And if you don't that's okay you can respond too if you wish!

**Comment by qatroxx** [comment]
go to server.cpp and comment gamepacket print

**Comment by demonicbae** [comment]
idk i dont know the gamepacket print of the place ;-;

**Comment by qatroxx** [comment]
> idk i dont know the gamepacket print of the place ;-;

oke look
https://prnt.sc/tijvm1 comment that with // at line 66
https://prnt.sc/tijwba and this at line 145

**Comment by demonicbae** [comment]
i meant if u could place but the place wont work that's what i mean ;-;
thanks!
