### ISSUE TITLE
Group proxy connection

### ISSUE THREAD

**Issue by flossboss** [ama6nen/enetproxy#9]
If someone was to host it on a VPS, would there be a way to add /online command to see all users connected? (Is hosting proxy on VPS even possible?)

**Comment by ama6nen** [comment]
Yes, you can host proxy on a VPS, and instead of localhost, you would use the vps ip. But the online probably isn't something that can be added as a feature to the proxy itself

**Comment by flossboss** [comment]
How about like a /pc (proxy chat)

**Comment by ama6nen** [comment]
would need a server to host it on and not going to get one just for proxy chat redirector
