### ISSUE TITLE
Internal Proxy [Would People be interested?]

### ISSUE THREAD

**Issue by SpaceR3** [ama6nen/enetproxy#94]
Hello, this seems the right place to ask. Would anyone be interested in an Internal Proxy? How would it work: \
It would Hook to Growtopia Send Packet function which is really is to find, every time the function gets called, it will run your code and then jump back. For example, let's say, it is sending game_version command, you can change the parameters, let's say to 4.20, and then jump back, it would be a lot better than an external proxy since you do not need to start an external enet server, this would be helpful for new people. I could even do a C# API since a lot of Growtopia "coders" do not know c++. Would anyone be interested in it? Is there a point to make it?

**Comment by SpaceR3** [comment]
Kinda would be "Growtopia Gamesense/Skeet", just shittier

**Comment by demonicbae** [comment]
Well This idea might be good but... There's a problem... On ama6nen Proxy you already can Spoof growtopia Verison to 6.00 More than that would cause a anticheat ban... So do you mean you want to make it into a "Proxy application" instead of cmd.exe? But C# Or C++ I mean It's your choice man...

**Comment by tewni-svg** [comment]
> Well This idea might be good but... There's a problem... On ama6nen Proxy you already can Spoof growtopia Verison to 6.00 More than that would cause a anticheat ban... So do you mean you want to make it into a "Proxy application" instead of cmd.exe? But C# Or C++ I mean It's your choice man...

That is not what i meant. You obviously did not get what i meant.

**Comment by tewni-svg** [comment]
> Well This idea might be good but... There's a problem... On ama6nen Proxy you already can Spoof growtopia Verison to 6.00 More than that would cause a anticheat ban... So do you mean you want to make it into a "Proxy application" instead of cmd.exe? But C# Or C++ I mean It's your choice man...

Please, dont even try to talk about it, you do not know what even internal means right?

**Comment by qatroxx** [comment]
hueta

**Comment by tewni-svg** [comment]
> hueta

u ok?

**Comment by qatroxx** [comment]
> > hueta
> 
> u ok?

im  ok

**Comment by xAl0n3** [comment]
internal proxy lol

**Comment by tewni-svg** [comment]
> internal proxy lol

whats so funny?

**Comment by ama6nen** [comment]
This is just normal internal hooking a function, there are already multiple made for Growtopia (and yes for hooking both sending and receiving packets)

I've had one for around 2 years now and it's not hard to make one, especially if you are only looking to hook something like Sendpacket

You would need to find function signatures properly, and update offsets or patterns if you want it to work in new versions. Same goes for making structures containing something like player data which is a pain to update usually

**Comment by playingoDEERUX** [comment]
github.com/playingoDEERUX/GrowtopiaInternal    -    very dirty implementation of it.

**Comment by m1rvu** [comment]
growsense.cc
