### ISSUE TITLE
[HELP] Coding my Own external Proxy

### ISSUE THREAD

**Issue by tewni-svg** [ama6nen/enetproxy#96]
Hey, i am currently coding my own external proxy for growotpia. I have done all ENET setup and also read the documention. I made a HTTP server and pointed Growtopia to there. As the IP for Growtopia ENET to connect it gets 127.0.0.1, everything is correct. I even looked at how This (ama) proxy works, i am using the same logic. For some reason, this: 
```
while (_proxy_running) {
		while (enet_host_service(Client, &event, 0))
		{
			cout << ".";
			switch (event.type)
			{
			case ENET_EVENT_TYPE_CONNECT:
				cout << "Detected a Connection from: " << event.peer->address.host << ":" << event.peer->address.port << endl;
				enet_packet_destroy(event.packet);

				break;

			case ENET_EVENT_TYPE_RECEIVE:
				cout << "Got Packets\n";
				break;
			case ENET_EVENT_TYPE_DISCONNECT:
				cout << "Lost Connection\n";
				event.peer->data = NULL;

			}
		}
		Sleep(1);
	}
```
`while (enet_host_service(Client, &event, 0))` never gets higher than 0, never, Growtopia tries to connect to it, but it fails and my Server never gets it. Anyone has a idea why?

Here is my HTTP server growtopia server_data.php http://45.153.187.167/growtopia/server_data.php

(Its hosted on my VPS so no need to try to BOOT it down.)

**Comment by tewni-svg** [comment]
Note: I am currently only trying to get Growtopia to connect to here, please do not comment "well its not sending any packets to the real GT server" I know, my question was why isnt my, lets say, midman server getting any data / connections?

**Comment by qatroxx** [comment]
scam accounts from login packets 
omg

**Comment by MoanHawks** [comment]
-----> client
                         |
server local ----- <-Send Packet to Server & client gt
                         |
                         -----> server host ----> another server local
                 (Get packet then send to another server local)

> scam accounts from login packets
Yes is can scam people account after send packet login but i recommand just make self register like virtual account

**Comment by ama6nen** [comment]
You don't have newlines in your server_data.php, my proxy has newlines as does the real one.
That might be the issue, but I'm not sure
![a](https://i.imgur.com/1vF7lx1.png)

**Comment by tewni-svg** [comment]
That was the issue. Thank you so much, did not even think of that.
